collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.9564983
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#B4B4B4'
    - '#10120D'
    - '#6B6F5F'
    - '#3D4238'
  rhythmicContrast: 1
typography_spectrum: 0.8945895
layout_spectrum: 0.7112873
name: Chana Tagney
