layout_spectrum: 0.7112873
color:
  saturation: 0.3544776
  lightness: 0.1254122
  brandStrength: 0.4123134
  brandColors:
    - '#FFFFFF'
    - '#B4B4B4'
    - '#10120D'
    - '#6B6F5F'
    - '#3D4238'
  rhythmicContrast: 1
typography_spectrum: 0.8945895
name: Chana Tagney
